### ISSUE TITLE
Package-prefix examples

### ISSUE THREAD

**Issue by bep** [fatih/stopwatch#1]
Very nice, but it would be even more useful and easy to use if you prefixed the examples in README with the package name.

**Comment by fatih** [comment]
# Archived project. No maintenance. 

This project is not maintained anymore and is archived. Feel free to fork and
make your own changes if needed. For more detail read my blog post: [Taking an indefinite sabbatical from my projects](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks to everyone for their valuable feedback and contributions.
